@OrderManagementSystem_HostAddress = https://localhost:7089
# @name login
POST {{OrderManagementSystem_HostAddress}}/api/Auth/login
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
  "email": "user@example.com",
  "password": "Ashok@123"
}
####################
# @name GETOrders
GET {{OrderManagementSystem_HostAddress}}/api/Orders
Accept: application/json
Authorization: Bearer {{login.response.body.$.token}}
###

# @name CreateOrders
POST {{OrderManagementSystem_HostAddress}}/api/Orders
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}
{
  "productName": "Dove shampoo",
  "quantity": 1000,
  "unitPrice": 100000
}
###


